/* quit button*/
//$(document).ready((){
//$("#blanks form").submit(function(){
//  function closeWin() {
//  myWindow.close();
  }
});
});
/* quit button*/


// Back-end logic
function  numberArray(hard) {
  // Array to store the numbers generated by for loop
  var numbers = [];
  for (var i = 1; i <= hard; i++) {
    // Condition "pingpong", "pong" and "ping"
    if (( i % 3 === 0) && ( i % 5 === 0)) {

      numbers.push("pingpong")

    } else if ( i % 5 === 0) {

      numbers.push("pong")

    } else if ( i % 3 === 0){

      numbers.push("ping")

    } else {

        numbers.push(i)

      }
  }
  return numbers;
}

// Front-end logic
$(document).ready(function() {
  $("form#pong").submit(function(event) {
    event.preventDefault();

    // Clear the result field before displaying new result
    $("ul").empty();

    // Store user input as a number
    var  hard = parseInt($("input#hard").val());
    // Test

    // Don't accept negative number
    if ( hard < 0  ) {
      alert("This is not a positive number");
    }

    var display = numberArray(hard);
    // Test
    // console.log(result);

    for (var index = 0; index < display.length; index += 1) {
        $("ul#display").append("<li>" + display[index] + "</li>")
      }

  });
});
